global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "llama-api"
    static_configs:
      - targets: ["edge-node:8082", "edge-node:8083"]

  - job_name: "ubuntu-hardware"
    static_configs:
      - targets: ["edge-node:9100"]