{
 "title": "Llama.cpp Edge AI Metrics",
 "tags": [
  "llamacpp",
  "ai"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Tokens / Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(llamacpp:prompt_tokens_total[1m])",
     "legendFormat": "Prompt Tokens/s ({{instance}})"
    },
    {
     "expr": "rate(llamacpp:tokens_predicted_total[1m])",
     "legendFormat": "Predicted Tokens/s ({{instance}})"
    }
   ]
  },
  {
   "title": "Active Decode Calls (Requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(llamacpp:n_decode_total[1m])",
     "legendFormat": "Decode Calls/s ({{instance}})"
    }
   ]
  },
  {
   "title": "Max Tokens Context Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "llamacpp:n_tokens_max", "legendFormat": "Max Tokens ({{instance}})" }
   ]
  },
  {
   "title": "Average Prompt Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "llamacpp:prompt_tokens_seconds", "legendFormat": "Avg Throughput ({{instance}})" }
   ]
  }
 ]
}